### ISSUE TITLE
개발사항 정리해서 README.md 업데이트

### ISSUE THREAD

**Issue by jngbng** [bgpworks/boxhero-electron#19]
기억해야 할 사항들. (주요 이슈와 가능했던 대안들, 선택한 이유 등등)

- 전체 폴더 구조
- 세션 기억하기 위해 Webview를 썼다.
- 메뉴 / 프레임 커스터마이징을 위해 React / webpack 도입
- 자동 업데이트 관련 구현사항

**Comment by BitYoungjae** [comment]
ee8aa672d1d2594cc44716bbc8475554359c5262 1차 작성

보완할 부분이 있는지 확인 부탁드립니다.
