### ISSUE TITLE
쿠키 보존 안됨.

### ISSUE THREAD

**Issue by jngbng** [bgpworks/boxhero-electron#5]
기본적으로 모두 session cookie로 저장하는데,
앱을 껐다 켜면 모두 사라짐.

- 유저 로그인 정보
- 바코드 출력 셋팅 정보

등이 다 날아감. 브라우저에서 persistent cookie 로 바꾸면 가장 간편하게 해결됨.

**Comment by BitYoungjae** [comment]
![image](https://user-images.githubusercontent.com/3115669/95417903-2adccd00-0971-11eb-8e3f-5a09eb84878d.png)

**Comment by jngbng** [comment]
직접 띄우는게 아니라 webview 로 띄우면 해결된다고 함.
